### ISSUE TITLE
Lucky Rock not working with Tinker's Construct

### ISSUE THREAD

**Issue by Cronus3166** [someaddons/AdventuresAndDungeons#1]
**Describe the bug**
The item Lucky Rock doesn't proc when using a Tinker's Construct tool.

**To Reproduce**
1) With the item Lucky Rock in my inventory (and even on my hotbar in some tests).
2) I used a couple of normal Minecraft Iron and Stone Pickaxes and was able to have the Lucky Rock proc and give me extra items while mining. 
3) After using both a Copper and Iron Tinker's Construct Pickaxe, I was never able to see the Lucky Rock proc.
4) With all tools I went through two full uses of their durability. 

**Expected behavior**
While mining, Lucky Rock is suppose to proc (with a 1% chance) to drop extra items while mining. 

** Mod version **
2.4

** Logs **
[2021-06-08-3.log.gz](https://github.com/someaddons/AdventuresAndDungeons/files/6635284/2021-06-08-3.log.gz)
[2021-06-10-2.log.gz](https://github.com/someaddons/AdventuresAndDungeons/files/6635285/2021-06-10-2.log.gz)
Latest/Crash log

**Comment by someaddons** [comment]
ye thats more a bug of the lucky rocks mod, please report it there
