### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -131

### ISSUE THREAD

**Issue by LawntheLawn** [someaddons/AdventuresAndDungeons#10]
I get this Error whenever I try to open the world.
I played in creative for awhile to build some things up, and it seemed to run fine for a few weeks, however when I entered survival it almost immediately crashed and continues to crash every time I enter that world.
[crash-2021-08-22_01.36.13-client.txt](https://github.com/someaddons/AdventuresAndDungeons/files/7026647/crash-2021-08-22_01.36.13-client.txt)
This is the crash report I keep getting.

**Comment by someaddons** [comment]
fixed in 3.6
