### ISSUE TITLE
Xiroc's Dungeon Crawl bug? Causing server to crash

### ISSUE THREAD

**Issue by Neolakia** [someaddons/AdventuresAndDungeons#11]
**Describe the bug**
Players exploring new world, loaded a chunk that crashed the server. Server restarted, players logged back in. Crashed again, report stated item entity being ticked. Deleted entity, still crashed, but now it stated player being ticked. Teleported player out of chunk, no more crashes. Load chunk again, crash again, stating a block? is the problem. 4 crash reports attached, all in the order they happened.

** Mod version **
3.5

** Logs **
Latest/Crash log
[crash-2021-08-22_00.18.10-server.txt](https://github.com/someaddons/AdventuresAndDungeons/files/7026826/crash-2021-08-22_00.18.10-server.txt)
[crash-2021-08-22_00.24.54-server.txt](https://github.com/someaddons/AdventuresAndDungeons/files/7026827/crash-2021-08-22_00.24.54-server.txt)
[crash-2021-08-22_01.16.37-server.txt](https://github.com/someaddons/AdventuresAndDungeons/files/7026829/crash-2021-08-22_01.16.37-server.txt)
[crash-2021-08-22_01.28.34-server.txt](https://github.com/someaddons/AdventuresAndDungeons/files/7026830/crash-2021-08-22_01.28.34-server.txt)

**Comment by someaddons** [comment]
fixed in 3.6
