### ISSUE TITLE
Software was running, then started crashing

### ISSUE THREAD

**Issue by lheaton13** [someaddons/AdventuresAndDungeons#12]
**Describe the bug**
I was playing the mod on a server with no issues. My game crashed. I uninstalled the app, then tried to reinstall the app and I keep getting this error.

**Comment by Mtank023** [comment]
![239684781_537141774282511_4122416371747802894_n](https://user-images.githubusercontent.com/89362890/130372999-83ec9068-1450-4f9b-8078-4e8d42fff2e7.jpg)


It is this error he is having issues with Child Addon 470193

**Comment by xyroc** [comment]
Curseforge is having serverside issues at the moment, but this modpack seems to be working again now.

**Comment by someaddons** [comment]
fixed in 3.6
