### ISSUE TITLE
Substantial lag while game is saving.

### ISSUE THREAD

**Issue by Madaxeio** [someaddons/AdventuresAndDungeons#13]
**Describe the bug**
Server side of the game hangs while saving, causing substantial lag.

**To Reproduce**
1. Play the game either singleplayer or server
2. Watch how every so often waila says waiting for server

**Mod version**
A&D 3.6

**Debug stuff**
This is a spark logging only tick over 5 seconds. SaveFormat$LevelSave.func_237288_a_() takes 14 seconds to complete.
![savelag](https://user-images.githubusercontent.com/89565354/130902842-2cfb4577-91c6-452f-8712-21904c6f85ae.png)
https://spark.lucko.me/kUkfLZXfm3

This is a vanilla debug file running for only 17 seconds while this save function is running.
[profile-results-2021-08-25_23.42.11.txt](https://github.com/someaddons/AdventuresAndDungeons/files/7051668/profile-results-2021-08-25_23.42.11.txt)

**Comment by someaddons** [comment]
fixed in 3.7
