### ISSUE TITLE
[question] Incorrect MC version?

### ISSUE THREAD

**Issue by violetazx** [someaddons/AdventuresAndDungeons#14]
I have A&D 3.6 installed (through CurseForge), however on the title screen it shows it's MC v1.16.5. Is this just a display error? I also noticed in the CurseForge app, A&D is tagged as 1.16.5, though it's tagged correctly on the website and shows up in 1.17.1 search results.

Edit: tried to install Inventory HUD+ and got an error saying I was running MC v1.16.5 so A&D is definitely running 1.16.5 despite downloading from the 1.17.1 files.

**Comment by Rosealia** [comment]
My partner and I are both having this current issue as well. We've tried reinstalling it several times.

**Comment by someaddons** [comment]
It is a 1.16.5 pack, curseforge tags have been bugged for a while
