### ISSUE TITLE
forge error

### ISSUE THREAD

**Issue by TakeoRenka** [someaddons/AdventuresAndDungeons#18]
as soon as i launch the pack it tells me it needs a newer version of forge for 3 of the mods
![Capture](https://user-images.githubusercontent.com/71478712/163523751-50a3c3f4-331e-40cf-9e0f-e61435ff561a.PNG)

**Comment by Luthien2903** [comment]
Im getting the same error and I cannot play the mod due to it.

**Comment by wfulcher** [comment]
I am also getting the same error. I did try to revert back several mods to fix it. To the point that I just reverted to an older version of the pack.
