### ISSUE TITLE
Friend can't join my LAN world

### ISSUE THREAD

**Issue by Meowzsa** [someaddons/AdventuresAndDungeons#2]
Me and my friend have always played via hamachi LAN Worlds.. But this modpack is not coming through at all!!!! He keeps getting kicked out. Saying "Internal server error"

**Comment by Wedge1453** [comment]
I think it's because of the mod "Antique Atlas"

**Comment by Meowzsa** [comment]
> I think it's because of the mod "Antique Atlas"

Thank you so much!! Indeed this was the problem.

**Comment by someaddons** [comment]
Lan mode  has issues in general, its recommened to just use a local server instead
