### ISSUE TITLE
Internal Server Error?

### ISSUE THREAD

**Issue by thepinkmuffin** [someaddons/AdventuresAndDungeons#4]
So I'm trying to play with a friend on LAN on the 3.4 version on the pack, I'm using curseforge.

Every time I tried to connect, it would act like it would load in the world like it would say ThePinkMuffin joined the game and then immediately say I left the game and give me the error "Internal Server Error" 

Is this an issue on my end or...?

**Comment by someaddons** [comment]
Lan mode usually has issues and is untested. I always suggest using a local server instead, simply go to https://files.minecraftforge.net/net/minecraftforge/forge/ download the latest 1.16.5 and install a server into an empty folder.
Then copy over the mods/configs from the serverpack upload
