### ISSUE TITLE
Crash when holding Farmers Delight Food

### ISSUE THREAD

**Issue by EinVoidling** [someaddons/AdventuresAndDungeons#5]
Since today my client keeps crashing after joining our server as soon as i try to hold Farmers Delight food in my hand in order to eat something
[crash-2021-08-11_17.30.34-client.txt](https://github.com/someaddons/AdventuresAndDungeons/files/6969644/crash-2021-08-11_17.30.34-client.txt)

**Comment by someaddons** [comment]
you somehow got into negative food values and the food rendering overlay is crashing, delete the appleskin mod, then login and eat till you got normal food again and then you can add the appleskin mod back
