### ISSUE TITLE
I don't have the 1.17 version, but 1.17 is showing up on curseforge.

### ISSUE THREAD

**Issue by CKenJa** [someaddons/AdventuresAndDungeons#8]
**Describe the bug**
I don't have the 1.17 version, but 1.17 is showing up on curseforge.

I believe it was a mistake, not a scam.
** Modpack version **
3.5

**Comment by someaddons** [comment]
![image](https://user-images.githubusercontent.com/38401808/130318652-80b88e7f-164d-40d0-8f76-83099d74f68a.png)

I'm not sure why, but somehow the tags are bugged. They just stay
