### ISSUE TITLE
Cannot find child addon file: 3279446 

### ISSUE THREAD

**Issue by rotmarone** [someaddons/AdventuresAndDungeons#9]
![error](https://user-images.githubusercontent.com/89318641/130333214-5b294b4b-c7a5-4ee1-bd29-ab0aafdfd849.PNG)
Hello, 
I wanted to download the Modpack from you. But then that massage came: Cannot find child addon file: 3279446.
I tried it with many versions of the pack but it was everywhere the same. If thats a problem others may also have maybe u can find a fix? I really would like to try the pack :D There is also a screenshot of the message.

**Comment by someaddons** [comment]
pack is working fine, its just curseforge itself having issues today^^. Just retry/try later again
